### ISSUE TITLE
Limiter le déplacement

### ISSUE THREAD

**Issue by ipante** [Tchetchouille/depression-in-vr#9]
Empêcher de traverser les murs et d'aller sur le balcon. Déterminer s'il est possible d'aller sur le lit.

A noter : vous pouvez aussi décider de forcer l'immobilisme (je suis assis sur la chaise, ne peux me déplacer, juste pivoter sur la chaise). Je ne suis pas sûr de le recommander (on perd le côté "hamster dans sa cage") d'une circulation vaine).

**Comment by Tchetchouille** [comment]
L'expérience a été pensée pour une utilisation avec le cardboard. L'immobilisme aurait donc en effet dû être présent sur la première version. Il s'agit d'une erreur de ma part. 

Je n'avais pas pensé au côté "hamster dans sa cage". C'est là une remarque très intéressante. Cependant, le déplacement complique le design d'une pièce qui évolue dans le dos des joueur·euse·x·s (qui est très faiblement développé dans sa version actuelle, mais qui le sera plus dans des versions ultérieures).

**Comment by ipante** [comment]
Ok, je comprends ! Dans ce cas, en effet, l'absence de déplacement fait complètement sens. Dans ce cas, il faut vraiment jouer avec les angles morts (quand je suis face à la porte, quelque chose peut changer sur l'écran, etc.) On se trouve du coup dans une situation "livre dont vous êtes le héros" si je regarde la porte, je ne regarde pas l'ordinateur et vice-versa.
